**O código nessa tarefa foi modificado a partir do tutorial: https://victorzhou.com/blog/keras-neural-network-tutorial/**

In [ ]:
pip install tensorflow numpy mnist


MNIST is a database of handwritten digits.

In [ ]:
import numpy as np
import mnist
from tensorflow import keras


Importing train and test datasets:

In [ ]:
train_images = mnist.train_images()
train_labels = mnist.train_labels()
test_images = mnist.test_images()
test_labels = mnist.test_labels()


In [ ]:
print(train_images[0:2])

[[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]


Pixel values varies from 0 to 255, since neural network processeses use small weight values, large inputs can interrupt or slow down the learning process. Therefore, it is a good practice to normalize pixel values: 

In [ ]:
# Normalize the images.
train_images = (train_images / 255) - 0.5
test_images = (test_images / 255) - 0.5


In [ ]:
print(train_images[0].shape)

(28, 28)


Images in the dataset are 28x28 pixels. Each image will be flattened to an array of 784 elements, observe that the transformation doesn't change the image size:

In [ ]:
# Flatten the images.
train_images = train_images.reshape((-1, 784))  
test_images = test_images.reshape((-1, 784))

print(train_images.shape) # (60000, 784)
print(test_images.shape)  # (10000, 784)

(60000, 784)
(10000, 784)


The Sequential model, from Tensorflow-Keras  library, is a linear stack of layers, which means that the output of one layer is the input of the layer below. The input shape needs to be specified on the first layer from our model. It corresponds to flattened image's shape (784): 

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense,Dropout

# Still a WIP
model = Sequential([
  Dense(64, activation='relu',input_shape=(784,)),
  Dropout(0.2),
  Dense(64, activation='relu'),
  Dropout(0.2),
  Dense(10, activation='softmax'),
])



64 is the number of nodes, and the dimensionality of the output space. The last layer has output dimensionality 10, one for each digit (0 to 9). Next, we must compile our model. This step is responsible for configuring the training process: 

In [ ]:
model.compile(
  optimizer='adam',
  loss='categorical_crossentropy',
  metrics=['accuracy'],
)

**Optimizer -** responsible for changing attributes, such as learning rate and weights, from the neural network in order to minimize the loss.

**loss -** measures the performance of a model. Since we use Softmax activation function as output in our model, we choose the categorical crossentropy loss function because it measures the performance of a model whose output is a probability value between 0 and 1.  

**metrics -** there are a variety of metrics used to evaluate a model. The one used in this example is accuracy, used to evaluate classification models.  

# **Training the model**


In [ ]:
from tensorflow.keras.utils import to_categorical


model.fit(
  train_images,
  to_categorical(train_labels),
  epochs=8, #inicial 5
  batch_size=50,  #inicial 32
)



Epoch 1/8
1200/1200 [==============================] - 2s 2ms/step - loss: 0.5690 - accuracy: 0.8210
Epoch 2/8
1200/1200 [==============================] - 2s 2ms/step - loss: 0.3388 - accuracy: 0.8962
Epoch 3/8
1200/1200 [==============================] - 2s 2ms/step - loss: 0.2860 - accuracy: 0.9122
Epoch 4/8
1200/1200 [==============================] - 2s 2ms/step - loss: 0.2608 - accuracy: 0.9186
Epoch 5/8
1200/1200 [==============================] - 2s 2ms/step - loss: 0.2470 - accuracy: 0.9246
Epoch 6/8
1200/1200 [==============================] - 2s 2ms/step - loss: 0.2328 - accuracy: 0.9290
Epoch 7/8
1200/1200 [==============================] - 2s 2ms/step - loss: 0.2197 - accuracy: 0.9330
Epoch 8/8
1200/1200 [==============================] - 2s 2ms/step - loss: 0.2161 - accuracy: 0.9354




# **Evaluating the model**

In [ ]:
model.evaluate(
  test_images,
  to_categorical(test_labels)
)

313/313 [==============================] - 0s 947us/step - loss: 0.1385 - accuracy: 0.9586


[0.1384877860546112, 0.9585999846458435]

# **Using the Model**

Saving weights:

In [ ]:
model.save_weights('/content/drive/My Drive/Colab Notebooks/DL/Ex_1/model.h5') #saving model to disk


Loading layer weights, either from a TensorFlow or an HDF5 weight file:

In [ ]:
# Load the model's saved weights.
model.load_weights('model.h5')

# **Making predictions**

In [ ]:
# Predict on the first 5 test images.
predictions = model.predict(test_images[:5])

# Print our model's predictions.
print(np.argmax(predictions, axis=1)) # [7, 2, 1, 0, 4]

# Check our predictions against the ground truths.
print(test_labels[:5]) # [7, 2, 1, 0, 4]

[7 2 1 0 4]
[7 2 1 0 4]
